raw_input() not found.
raw_input() was renamed input() in python 3. I'm not sure why it was changed back to raw_input(), maybe python2 was run on the file even though the header has python3? Otherwise this error occurs:

  File "kill_dupes", line 118, in <module>
    if query_yes_no("Found " + str(len(duplicate_track_ids)) + " duplicate tracks. Delete duplicates?", "no"):
  File "kill_dupes", line 90, in query_yes_no
    choice = raw_input().lower()
NameError: name 'raw_input' is not defined